### ISSUE TITLE
OSGi Runtime with ClassNotFoundException: com.lowagie.text.FontFactory

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1149]
### Discussed in https://github.com/eclipse/birt/discussions/1142

<div type='discussions-op-text'>

<sup>Originally posted by **blatra** December 20, 2022</sup>
Hello Team,

I updated the BIRT OSGi runtime used in our application (deployed on WildFly 27, running on java 11) from version 4.8 to 4.10.
When I try to generate a report I get a `java.lang.ClassNotFoundException: com.lowagie.text.FontFactory`.

I also tried BIRT 4.12, but I get the same error:

```
SCHWERWIEGEND: Error happened while running the report.
java.lang.NoClassDefFoundError: com/lowagie/text/FontFactory
	at org.eclipse.birt.report.engine.layout.pdf.font.FontMappingManagerFactory$1.run(FontMappingManagerFactory.java:201)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.birt.report.engine.layout.pdf.font.FontMappingManagerFactory.registerJavaFonts(FontMappingManagerFactory.java:195)
	at org.eclipse.birt.report.engine.layout.pdf.font.FontMappingManagerFactory.<init>(FontMappingManagerFactory.java:147)
	at org.eclipse.birt.report.engine.layout.pdf.font.FontMappingManagerFactory.getInstance(FontMappingManagerFactory.java:83)
	at org.eclipse.birt.report.engine.nLayout.LayoutContext.getFontManager(LayoutContext.java:302)
	at org.eclipse.birt.report.engine.nLayout.area.impl.TextAreaLayout.<init>(TextAreaLayout.java:74)
	at org.eclipse.birt.report.engine.nLayout.area.impl.InlineTextArea.layout(InlineTextArea.java:57)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.startContent(LayoutEngine.java:425)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterAdapter.startText(ContentEmitterAdapter.java:148)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterAdapter.startLabel(ContentEmitterAdapter.java:154)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.startContent(ContentEmitterUtil.java:64)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.visitContent(LayoutEngine.java:551)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.visitContent(LayoutEngine.java:557)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.visitChildren(LayoutEngine.java:569)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ForeignHTMLRegionLayout$ForeignHTMLRegionLayoutEngine.layout(ForeignHTMLRegionLayout.java:85)
	at org.eclipse.birt.report.engine.nLayout.area.impl.ForeignHTMLRegionLayout.layout(ForeignHTMLRegionLayout.java:51)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.processHTML(LayoutEngine.java:621)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.startForeign(LayoutEngine.java:580)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.startContent(ContentEmitterUtil.java:76)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.visitContent(LayoutEngine.java:551)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.visitChildren(LayoutEngine.java:569)
	at org.eclipse.birt.report.engine.nLayout.RegionLayoutEngine.layout(RegionLayoutEngine.java:30)
	at org.eclipse.birt.report.engine.nLayout.area.impl.PageArea.layoutFooter(PageArea.java:381)
	at org.eclipse.birt.report.engine.nLayout.area.impl.PageArea.initialize(PageArea.java:209)
	at org.eclipse.birt.report.engine.nLayout.area.impl.RootArea.createNewPage(RootArea.java:128)
	at org.eclipse.birt.report.engine.nLayout.area.impl.RootArea.initialize(RootArea.java:120)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.setContainer(LayoutEngine.java:295)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine._startContainer(LayoutEngine.java:349)
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.startContainer(LayoutEngine.java:285)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterAdapter.startPage(ContentEmitterAdapter.java:67)
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.startContent(ContentEmitterUtil.java:46)
	at org.eclipse.birt.report.engine.layout.html.buffer.PageNode.start(PageNode.java:45)
	at org.eclipse.birt.report.engine.layout.html.buffer.ContainerBufferNode.start(ContainerBufferNode.java:70)
	at org.eclipse.birt.report.engine.layout.html.buffer.ContainerBufferNode.flush(ContainerBufferNode.java:44)
	at org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer._endContainer(HTMLPageBuffer.java:144)
	at org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer.endContainer(HTMLPageBuffer.java:131)
	at org.eclipse.birt.report.engine.layout.html.buffer.TableBreakBuffer.endContainer(TableBreakBuffer.java:257)
	at org.eclipse.birt.report.engine.layout.html.HTMLTableLM.end(HTMLTableLM.java:49)
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:134)
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66)
	at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92)
	at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:97)
	at org.eclipse.birt.report.engine.presentation.ReportDocumentBuilder.build(ReportDocumentBuilder.java:226)
	at org.eclipse.birt.report.engine.api.impl.RunTask.doRun(RunTask.java:224)
	at org.eclipse.birt.report.engine.api.impl.RunTask.run(RunTask.java:85)
	at deployment.birtapp.ear.remote.jar//de.birtapp.ReportGen.runTask(ReportGen.java:1240)
	at deployment.birtapp.ear.remote.jar//de.birtapp.ReportGen.call(ReportGen.java:919)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.FontFactory cannot be found by org.eclipse.birt.report.engine_4.12.0.v202211281949
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 52 more
```

I've seen that [iText has been replaced with OpenPDF](https://github.com/eclipse/birt/issues/767). Maybe this change is related to my problem.

Do you have an idea what may cause my problem or what I can do to investigate further?

Thanks in advance.</div>

**Comment by speckyspooky** [comment]
With the latest built of the 4.14 the openpdf version is updated to version 1.3.30.
So you can test the newest built if it is solved in your solution.

I will close the issue but if you should have further topics with that, we can reopen the issue.
