### ISSUE TITLE
Unable to generate xlsx report 

### ISSUE THREAD

**Issue by marmcn** [eclipse-birt/birt#1308]
Hello, 

When attempting to export a report as xlsx the render step of the report processing fails with the following exception:

Caused by: java.lang.NoSuchMethodError: **Method not implemented: FlattenedListHandler.startTable
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractHandler.startTable**(AbstractHandler.java:192) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.startTable(ExcelEmitter.java:297) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.emitter.CompositeContentEmitter.startTable(CompositeContentEmitter.java:264) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.startTable(HTMLTableLayoutEmitter.java:337) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.startTable(HTMLTableLayoutEmitter.java:334) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.startContent(ContentEmitterUtil.java:49) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.ContainerBufferNode.start(ContainerBufferNode.java:73) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.ContainerBufferNode.start(ContainerBufferNode.java:70) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.ContainerBufferNode.start(ContainerBufferNode.java:70) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer.startContent(HTMLPageBuffer.java:100) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.TableBreakBuffer.startContent(TableBreakBuffer.java:226) ~[org.eclipse.birt.runtime_4.9.0-20220315.jar:?]

The FlattenedListHandler called by the emitter does not implement the startTable() function from AbstractHandler.
I have read in some previous threads that HTMLTable is not supported, however, ideally the report generation shouldn't be broken altogether. The report generates ok with the standard XLS emitter.

**Comment by hvbtup** [comment]
Can you give a minimal example report (no external dependencies) demonstrating the issue?

**Comment by speckyspooky** [comment]
@marmcn Could you provide an example like requeted before or let us also know if the topic is outdated then we will close the issue.

**Comment by speckyspooky** [comment]
The issue will be corrected with PR #1433

**Comment by speckyspooky** [comment]
The changes to avoid the issue are included at PR #1433 of BIRT 4.14
