### ISSUE TITLE
Fatal error occurred when try to startup report engine.

### ISSUE THREAD

**Issue by shahzad80** [eclipse-birt/birt#1328]
**This is my current configuration** 

Rocky Linux 8.8
Tomcat server 9
Viewer Version: 4.13.0
Engine Version: 4.13.0
JRE version: 11.0.19

I have received data from the MIS dept provided data of birt reporting which was handled by below configuration

Centos 6
Tomcat server 7
Viewer Version: 2.5.1
Engine Version: 2.5.1
java-1.8.0-openjdk.x86_64

Home page is displaying fine but view example link shows this error.

- Fatal error occurred when try to startup report engine.
org.eclipse.birt.report.exception.ViewerException: Fatal error occurred when try to startup report engine.
	at org.eclipse.birt.report.service.ReportEngineService.setEngineContext(ReportEngineService.java:328)
	at org.eclipse.birt.report.service.BirtViewerReportService.setContext(BirtViewerReportService.java:1022)
	at org.eclipse.birt.report.servlet.ViewerServlet.__getContext(ViewerServlet.java:148)
	at org.eclipse.birt.report.servlet.BirtSoapMessageDispatcherServlet.doGet(BirtSoapMessageDispatcherServlet.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.axis.transport.http.AxisServletBase.service(AxisServletBase.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.eclipse.birt.report.servlet.BirtSoapMessageDispatcherServlet.service(BirtSoapMessageDispatcherServlet.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.eclipse.birt.report.filter.ViewerFilter.doFilter(ViewerFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

does this old configuration will not work with my new server

Thanks.

**Comment by shahzad80** [comment]
Thank you again for your reply.

yes, I guess stack trace does not belong to the 4.13 release it is running fine, and just copied the given data on the web apps folder and if I click on it shows birt homepage and after clicking on view example link it shows a fatal error.

![image](https://github.com/eclipse-birt/birt/assets/61746668/9eafa97d-6933-4bc3-a18f-e1b539323276)

![image](https://github.com/eclipse-birt/birt/assets/61746668/a29494ab-2cba-4b70-b484-ff7f8a343c5d)

![image](https://github.com/eclipse-birt/birt/assets/61746668/c3d511b9-b586-415f-8abd-9fbc893bd4bd)

**Comment by shahzad80** [comment]
I switched Java version 11 to 1.8 and resulted from stop working Both links that are birt 2.5.1 and 4.13

complete log entries of catalina.2023-06-12.log
[catalina-2023-06-12.txt](https://github.com/eclipse-birt/birt/files/11717931/catalina-2023-06-12.txt)

complete log entries of localhost_access_log.2023-06-12
[localhost_access_log.2023-06-12.txt](https://github.com/eclipse-birt/birt/files/11717947/localhost_access_log.2023-06-12.txt)

I have attached log files for further reference.

Thanks.

**Comment by claesrosell** [comment]
You should use Java11.
I will try to reproduce this on my Linux machine with Tomcat 9 and Birt 4.13.

**Comment by shahzad80** [comment]
I am using java 11.

one thing I didn't understand that data was copied into web apps folder name bank does not have **.war** file in it so why does it display BIRT version 2.5.1. reports are in bank folder and should work with latest birt 4.13 version.

**Comment by merks** [comment]
@speckyspooky 

Note that as we plan to release 4.14 relatively soon, when I see issues like this I wonder "does this actually work for 4.14"?

**Comment by shahzad80** [comment]
@merks @speckyspooky 

index.jsp file is in bank folder that belongs to an older version of birt 2.5.1.

should it be replaced with new version of jsp file so by doing this would it work

Thanks

**Comment by shahzad80** [comment]
> You should use Java11. I will try to reproduce this on my Linux machine with Tomcat 9 and Birt 4.13.

but you need to put the data in the web apps folder that belongs to older version of BIRT

**Comment by claesrosell** [comment]
I am sorry, but I do not understand what it is you are trying to do. Can you explain in detail what you have done?

It sounds like you try to have two versions of Birt installed on the same Tomcat. If you are trying that: you are out of luck. All deployed web applications share the same JVM, so you will have classloading issues if you try to do that.

**Comment by shahzad80** [comment]
Thank you for your reply.

no, I am not running two different sessions on the Tomcat server.

I just explained in an earlier message that I just copied data into web apps folder which is present on the other server and it has birt older version like 2.5.1. in this data folder no birt.war file is present but it is using an older version of the homepage.

**Comment by claesrosell** [comment]
You will need to provide a detailed description of how to reproduce the encountered issue.
As it is now, I have no idea how to reproduce this issue, and if we cannot reproduce it, we cannot fix it.

You say in one of the comments that the stacktrace probably does not belong to a 4.13 instance since that one is "running fine". And that we should "put the data in the web apps folder that belongs to older version of BIRT" -to make it fail.  If that data is needed to reproduce the error you need to provide it.

**Comment by shahzad80** [comment]
Thank you for your reply.

This is a complete status of manager apps

![image](https://github.com/eclipse-birt/birt/assets/61746668/f5b7acd1-04bf-4485-b3f8-a98ad2e303ce)

you can see that there is two link name **birt** and **bank**  both displaying together with upper and lower direction.

birt has a new version 4.13 and it successfully launched its test report.

![image](https://github.com/eclipse-birt/birt/assets/61746668/1c079c53-6c90-4b81-97c9-8f0a59d5fe8d)

![image](https://github.com/eclipse-birt/birt/assets/61746668/e44ea655-24c9-4c52-8b59-0f0b5e8b4e5c)

when I come on the bank link it shows this home page

![image](https://github.com/eclipse-birt/birt/assets/61746668/d467e677-29d9-4a58-808b-6855c253bed9)

i test this example link then it shows a fatal error

![image](https://github.com/eclipse-birt/birt/assets/61746668/9e03666a-b21c-4c84-aa17-13f488797634)

so that's why said trace is not belong to 4.13 because it is working fine.

according to my understanding if I put two **birt.war** files into different folders so Tomcat creates multiple sessions against two files.

if I am mistaken on this point then please correct me.

I have only one birt.war file into the web apps folder.

![image](https://github.com/eclipse-birt/birt/assets/61746668/7a2a31bb-e82a-4d22-b5ac-661d91170821)
