### ISSUE TITLE
Caused by: org.eclipse.birt.report.model.parser.DesignParserException: The report file of version "3.2.24" is invalid for it is greater than the latest supported one.

### ISSUE THREAD

**Issue by rcckie** [eclipse-birt/birt#1465]
Hi admin,
 I'm using the Spring Boot system with Java JDK 1.8. I've designed a .rptdesign file using BIRT Report Designer 4.12, but when I try to export it to xlsx in Java 1.8, I encounter the error as mentioned in the title. I've tried replacing all the BIRT runtime libraries from 3.7 to 4.5 and even 4.13, but none of them worked. It seems like there might be an incompatibility issue with the Java version or some other problem that I don't understand. Please guide me on how to resolve this. Thank you.

![Screenshot 2023-10-30 235609](https://github.com/eclipse-birt/birt/assets/93069838/21cf0b79-f6f4-43fb-bb9b-c4044e94a41d)
![Screenshot 2023-10-30 235609](https://github.com/eclipse-birt/birt/assets/93069838/4c3ac122-51bc-468f-b71a-eb1dcbc7758f)

**Comment by speckyspooky** [comment]
Have your tried to reset your report version number from "3.2.24" to "3.2.23". May be you can give them a try.

**Comment by rcckie** [comment]
@speckyspooky  
I got rid of the above error following your instructions. Thank you very much for that but I encountered a new problem. My rptdesign file is connecting to mongodb and when task.run() outputs xlsx file in java I get an error (as shown). i think the problem is in org.eclipse.birt.data.oda.mongodb as i am using jdk 1.8 . please help me how to solve this problem. thank you
![image](https://github.com/eclipse-birt/birt/assets/93069838/e52ed684-400b-4524-93c4-93124411b598)

**Comment by claesrosell** [comment]
I just want to say that, while you are free to use older versions of Birt than 4.9, none in the current dev team was involved in Birt when those versions were released.
A lot of work has been done to move away from legacy versions of Java. You will probably have better chances to get help with newer versions of Birt. From your original post, it seems like you are using a bit of a mix of Birt versions. Birt 4.9 requires JavaSE-11or higher. Next version of Birt will require JavaSE-17.

**Comment by rcckie** [comment]
> I just want to say that, while you are free to use older versions of Birt than 4.9, none in the current dev team was involved in Birt when those versions were released. A lot of work has been done to move away from legacy versions of Java. You will probably have better chances to get help with newer versions of Birt. From your original post, it seems like you are using a bit of a mix of Birt versions. Birt 4.9 requires JavaSE-11or higher. Next version of Birt will require JavaSE-17.

Thanks for answering. i am using birt designer 4.12.0 and birt runtime 4.4.1 . My prod java project is using jdk 1.8. There are many other libraries following. I can't upgrade it to jdk17 so I still want to use it in jdk1.8. I'm just having a problem with class "com.mongodb.ReadPreference"'s signer information does not match signer information of other classes in the same package when it comes to the IRunAndRenderTask.run() step

**Comment by claesrosell** [comment]
You wrote that:
>  I've tried replacing all the BIRT runtime libraries from 3.7 to 4.5 and even 4.13, but none of them worked.

That makes me believe that there is a mix of jars from different versions of the Birt distribution in your environment.
The error you have states that two classes from the same package are signed with different certificates, which also makes me believe that there are multiple versions of some jars on your classpath. Either that has been done by someone in your organization or someone else is trying to do something malicious.

Are you running Birt in an OSGI environment?

**Comment by merks** [comment]
I can only second with @claesrosell  says.  You'd be best to try with 4.14 which requires Java 17 because that will be the next release, so using it helps us test it.  Furthermore, there will be no support for fixing problems other than problems in 4.14 version.

**Comment by rcckie** [comment]
Thank you everyone for giving me advice. I have resolved old errors and encountered new errors. It seems that it cannot connect to my mongodb when reading data using birt runtime and gives an error as shown in the image. but on my birt design. everything still runs normally

![image](https://github.com/eclipse-birt/birt/assets/93069838/e4ee089d-3372-4211-99e1-4c6435ed9a81)

**Comment by claesrosell** [comment]
Is that the complete stacktrace? I get a feeling that there are "causedBy" exceptions missing.
Also, being far from en expert on MongoDB, it looks like you provide the wrong server address to your database.
It says : "serverUsed" : /103.214.9.131:27117" 
I guess that it should be : "http://103.214.9.131:27117" or "https://103.214.9.131:27117"

**Comment by rcckie** [comment]
> Is that the complete stacktrace? I get a feeling that there are "causedBy" exceptions missing. Also, being far from en expert on MongoDB, it looks like you provide the wrong server address to your database. It says : "serverUsed" : /103.214.9.131:27117" I guess that it should be : "http://103.214.9.131:27117", "https://103.214.9.131:27117" or "mongodb://103.214.9.131:27117" . To start a connection string with a slash is not common.

@claesrosell It seems that mongodb on dependency 4.4.1 is not fully supported like on birt designer 4.12 . There are a few properties that Java says are not supported.

Nov 01, 2023 3:23:03 PM uk.co.spudsoft.birt.emitters.excel.framework.Logger info
INFO: start:org.eclipse.birt.report.engine.content.impl.ReportContent@52a36910
Nov 01, 2023 3:23:03 PM com.mongodb.MongoClientURI parseOptions
WARNING: Unknown or Unsupported Option 'authsource'
Nov 01, 2023 3:23:03 PM com.mongodb.MongoClientURI parseOptions
WARNING: Unknown or Unsupported Option 'retrywrites'
Nov 01, 2023 3:23:04 PM com.mongodb.MongoClientURI parseOptions
WARNING: Unknown or Unsupported Option 'authsource'
Nov 01, 2023 3:23:04 PM com.mongodb.MongoClientURI parseOptions
WARNING: Unknown or Unsupported Option 'retrywrites'
Nov 01, 2023 3:23:04 PM org.eclipse.birt.data.engine.odaconsumer.ConnectionManager openConnection
SEVERE: Unable to open connection.
org.eclipse.datatools.connectivity.oda.OdaException ;
     com.mongodb.CommandResult$CommandFailure: command failed [listDatabases]: { "serverUsed" : "/103.214.9.131:27117" , "operationTime" : { "$ts" : 1698826989 , "$inc" : 1} , "ok " : 0.0 , "errmsg" : "command listDatabases requires authentication" , "code" : 13 , "codeName" : "Unauthorized" , "$clusterTime" : { "clusterTime" : { "$ts" : 1698826989 , "$inc " : 1} , "signature" : { "hash" : <Binary Data> , "keyId" : 7267822084946919428}}}
at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.existsDatabase(MDbConnection.java:246)
at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.getMongoDatabase(MDbConnection.java:83)
at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.open(MDbConnection.java:50)
at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaConnection.open(OdaConnection.java:250)
at org.eclipse.birt.data.engine.odaconsumer.ConnectionManager.openConnection(ConnectionManager.java:165)
at org.eclipse.birt.data.engine.executor.DataSource.newConnection(DataSource.java:224)
at org.eclipse.birt.data.engine.executor.DataSource.open(DataSource.java:212)
at org.eclipse.birt.data.engine.impl.DataSourceRuntime.openOdiDataSource(DataSourceRuntime.java:217)
at org.eclipse.birt.data.engine.impl.QueryExecutor.openDataSource(QueryExecutor.java:434)
at org.eclipse.birt.data.engine.impl.QueryExecutor.prepareExecution(QueryExecutor.java:322)
at org.eclipse.birt.data.engine.impl.PreparedQuery.doPrepare(PreparedQuery.java:463)
at org.eclipse.birt.data.engine.impl.PreparedDataSourceQuery.produceQueryResults(PreparedDataSourceQuery.java:190)
at org.eclipse.birt.data.engine.impl.PreparedDataSourceQuery.execute(PreparedDataSourceQuery.java:178)
at org.eclipse.birt.data.engine.impl.PreparedOdaDSQuery.execute(PreparedOdaDSQuery.java:178)
at org.eclipse.birt.report.data.adapter.impl.DataRequestSessionImpl.execute(DataRequestSessionImpl.java:637)
at org.eclipse.birt.report.engine.data.dte.DteDataEngine.doExecuteQuery(DteDataEngine.java:152)
at org.eclipse.birt.report.engine.data.dte.AbstractDataEngine.execute(AbstractDataEngine.java:275)
at org.eclipse.birt.report.engine.executor.ExecutionContext.executeQuery(ExecutionContext.java:1947)
at org.eclipse.birt.report.engine.executor.QueryItemExecutor.executeQuery(QueryItemExecutor.java:80)
at org.eclipse.birt.report.engine.executor.TableItemExecutor.execute(TableItemExecutor.java:62)
at org.eclipse.birt.report.engine.internal.executor.dup.SuppressDuplicateItemExecutor.execute(SuppressDuplicateItemExecutor.java:43)
at org.eclipse.birt.report.engine.internal.executor.wrap.WrappedReportItemExecutor.execute(WrappedReportItemExecutor.java:46)
at org.eclipse.birt.report.engine.internal.executor.l18n.LocalizedReportItemExecutor.execute(LocalizedReportItemExecutor.java:34)
at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:65)
at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92)
at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:100)
at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:181)
at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.run(RunAndRenderTask.java:77)
at com.migi.sss.Main.main(Main.java:43)
Caused by: com.mongodb.CommandResult$CommandFailure: command failed [listDatabases]: { "serverUsed" : "/103.214.9.131:27117" , "operationTime" : { "$ts" : 1698826989 , "$inc" : 1} , "ok" : 0.0 , "errmsg" : "command listDatabases requires authentication" , "code" : 13 , "codeName" : "Unauthorized" , "$clusterTime" : { "clusterTime" : { "$ts" : 1698826989 , "$inc" : 1} , "signature" : { "hash" : <Binary Data> , "keyId" : 7267822084946919428}}}
at com.mongodb.CommandResult.getException(CommandResult.java:88)
at com.mongodb.CommandResult.throwOnError(CommandResult.java:134)
at com.mongodb.Mongo.getDatabaseNames(Mongo.java:394)
at org.eclipse.birt.data.oda.mongodb.impl.MDbConnection.existsDatabase(MDbConnection.java:242)

**Comment by claesrosell** [comment]
There are most certainly things in recent MongoDB that Birt 4.4.1 is not supporting.

It is important to understand that Birt 4.4.1 is almost 10 years old. It was released when MongoDB v2.6 was the most bleeding edge version. I do not know what version of MongoDB you are using, but v7 was recently released.
SCRAM, which is the default authentication mechanism in MongoDB was introduced in v3, which was released after Birt 4.4.1

**Comment by speckyspooky** [comment]
My point of view would be to ignore the integrated mongoDB-driver and user the common oda-jdbc-interface of BIRT.
There you can configure all jdbc driver based on the driver manager and you can connect to the databse which you plan to use with the latest driver from the database.
Then you are independent in full, you are able to use the latest database driver. And in best case this would help you to fix the issue.
