### ISSUE TITLE
New issue with null values for decimal DS parameters

### ISSUE THREAD

**Issue by hvbtup** [eclipse-birt/birt#1520]
My fork includes the commit #1371: "Fix prepared statement setNull() #1365"

I cannot generate a report without a lot of stack trace output in the following situation.

I am using the Oracle JDBC driver.

A parent dataset selects a column IADRNR_KUNDE which is defined as NUMBER(10) in the Oracle DB.
This contains an ID of an individual person. In BIRT, the datataype is shown as `decimal`.

A child dataset uses two input parameters: param_FIRM_ID (an ID of a company) and param_IADRNR (an ID of an individual person).
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/de76f753-94de-4bda-93ee-54053b22875e)

In the layout I have a structure like this:
A list (bound to he parent DS)
Inside the list's detail area, there are two items "Customer" and "Supplier", which both are bound to the child dataset.
 bound to the child dataset.

The first one uses IADRNR_KUNDE from the parent query:
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/4f953ba8-3584-49b7-b75f-84b672942271)
(I still use BIRT 4.2.1 for *developing* reports)

The second one uses `null`, because we don't want to output a person here, just the company address:
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/8015b2bb-3ea6-49c0-b4a1-c1a5085f1a50)

Running this report results in a BIRT error:
```
org.eclipse.birt.report.engine.api.EngineException: Cannot get the result set metadata.
    org.eclipse.birt.report.data.oda.jdbc.JDBCException: SQL statement does not return a ResultSet object.
SQL error #1:ORA-00932: Inkonsistente Datentypen: CHAR erwartet, NUMBER erhalten
 ;
```

Now I now that the valid values for IADRNR are > 0, so I tried to use `0` as a replacement for `null` (the SQL query is written in a way that it will treat the values `null` and `0` for the input parameter in the same way).

So I changed the parameter binding like this:
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/b208989b-6ead-429b-b31b-80437b09e29b)
and
![grafik](https://github.com/eclipse-birt/birt/assets/7644776/6406fd84-c7c4-4a1c-8521-bb72f0960cad)

With this change, the report works as expected, but there is a lot of stack trace output in the log:
```
Cannot get the type for parameter: 1.
org.eclipse.birt.report.data.oda.jdbc.JDBCException: Cannot get parameter type.
SQL error #1:Nicht unterstützte Funktion: checkValidIndex
 ;
    java.sql.SQLFeatureNotSupportedException: Nicht unterstützte Funktion: checkValidIndex
	at org.eclipse.birt.report.data.oda.jdbc.ParameterMetaData.getParameterType(ParameterMetaData.java:144)
	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaParameterMetaData.getParameterType(OdaParameterMetaData.java:177)
	at org.eclipse.birt.data.engine.odaconsumer.ParameterMetaData.getRuntimeParameterType(ParameterMetaData.java:217)
	at org.eclipse.birt.data.engine.odaconsumer.ParameterMetaData.<init>(ParameterMetaData.java:96)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.mergeParamHintsWithMetaData(PreparedStatement.java:1501)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getParameterMetaData(PreparedStatement.java:1380)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getParameterMetaData(PreparedStatement.java:1393)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getScaleValue(PreparedStatement.java:3676)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.doSetBigDecimal(PreparedStatement.java:3637)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.setBigDecimal(PreparedStatement.java:3304)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.setParameterValue(PreparedStatement.java:2655)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.setParameterValue(PreparedStatement.java:2592)
	at org.eclipse.birt.data.engine.executor.DataSourceQuery.setInputParameterBinding(DataSourceQuery.java:1031)
...
```

The next thing I tried was to use `java.math.BigDecimal(0)` instead of a `0` literal:

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/ff478b8d-24f1-4674-9c56-388e08a68f7d)

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/9e7d3bf0-9a5f-4308-8363-18c824731135)

![grafik](https://github.com/eclipse-birt/birt/assets/7644776/f3c2f12d-19e7-4c35-90b8-5e9d774bcd1f)

This has the same effect as using 0: The report works, but a lot of log output:

```
Cannot get the type for parameter: 1.
org.eclipse.birt.report.data.oda.jdbc.JDBCException: Cannot get parameter type.
SQL error #1:Nicht unterstützte Funktion: checkValidIndex
 ;
    java.sql.SQLFeatureNotSupportedException: Nicht unterstützte Funktion: checkValidIndex
	at org.eclipse.birt.report.data.oda.jdbc.ParameterMetaData.getParameterType(ParameterMetaData.java:144)
	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaParameterMetaData.getParameterType(OdaParameterMetaData.java:177)
	at org.eclipse.birt.data.engine.odaconsumer.ParameterMetaData.getRuntimeParameterType(ParameterMetaData.java:217)
	at org.eclipse.birt.data.engine.odaconsumer.ParameterMetaData.<init>(ParameterMetaData.java:96)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.mergeParamHintsWithMetaData(PreparedStatement.java:1501)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getParameterMetaData(PreparedStatement.java:1380)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getParameterMetaData(PreparedStatement.java:1393)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.getScaleValue(PreparedStatement.java:3676)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.doSetBigDecimal(PreparedStatement.java:3637)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.setBigDecimal(PreparedStatement.java:3304)
	at org.eclipse.birt.data.engine.odaconsumer.PreparedStatement.setParameterValue(PreparedStatement.java:2655)
...
```

I think that the whole input parameter handling always was and still is broken.
I mean, we explicitly specify the input parameter datatype in the DS definition (see the first screenshot), so why does ODA think it has to magically find out the parameter type in getParameterMetaData?

**Comment by speckyspooky** [comment]
The getParameterMetaData() isn't real a clever method. During my testing I figured out that th value "null" is the cause that the parameter object is null. It is independent of the data type because "null" mean the object will be null. This is independent of the source change it was the handling before.
I don't know why.

Question from my side:
Where you see the stack trace?
I ask you because I habe changed my test case but ist must be to simple in compare to your version.

1. I have dataset 01 "master-parent-loop"
2. I added in this table at detail level an inner table with a "slave-child-dataset"
3. The child-data-set use the binding-parameter from the master-parent-loop and the key value can be set to "null" but I cannot see your stack trace. I can only see the correct report result.

I use the web-viewer for execution and there isn't any error display on my console.
Both parameters defined like "decimal".

**Comment by hvbtup** [comment]
OK, I'm not really sure this is a new issue:
I usually try to avoid using numerical input parameters for JDBC datasets, but in this report it seemed to be the natural solution.
Maybe the same error occurs with an older BIRT release, I'll have to verify this.

I'm pretty sure it is related to the Oracle JDBC driver as well.
A few years ago, I created an Oracle support ticket ("TAR") regarding the original issue.
We then traced the JDBC calls and Oracle support told me that the sequence of JDBC statements didn't really make sense from their point of view.

Regarding "where do your see the stack trace?":
I am using a logging configuration where I redirect JUL to log4j (resp. reload4j). And that's logging to a RollingFileAppender.
I set the level to DEBUG for org.eclipse, org.eclipse.birt and org.eclipse.birt.data, but that's not really necessary, because the trace comes out with ERROR level.

No time ATM to supply further details, I hope I can add more this afternoon.

**Comment by hvbtup** [comment]
I tried to create a simple test report, but failed to reproduce the issue. Anyway, here it is:
[ora_jdbc_metadata_issue.zip](https://github.com/eclipse-birt/birt/files/13810804/ora_jdbc_metadata_issue.zip)
In order to run it, one needs to add the `ojdbc8.jar` from Oracle to the drivers directory and to set up the connection properties.

**Comment by wimjongman** [comment]
Please reopen if this is still an issue.
