### ISSUE TITLE
Install Birt Viewer on Ubuntu 22.04 and Tomcat10 fails

### ISSUE THREAD

**Issue by beccon4** [eclipse-birt/birt#1558]
Installing the BIRT viewer following the instructions here  https://eclipse-birt.github.io/birt-website/docs/integrating/viewer-setup fails with this messages:

```
28-Jan-2024 23:51:59.725 INFO [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log HTMLManager: start: Starting web application '/birt-viewer'
28-Jan-2024 23:52:06.536 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [ViewerFilter]
	java.lang.ClassCastException: class org.eclipse.birt.report.filter.ViewerFilter cannot be cast to class jakarta.servlet.Filter (org.eclipse.birt.report.filter.ViewerFilter is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @6371b178; jakarta.servlet.Filter is in unnamed module of loader java.net.URLClassLoader @2e0fa5d3)
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:243)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:98)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4304)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4911)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1416)
		at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:702)
		at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:220)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:563)
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:631)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:190)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:608)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:840)
28-Jan-2024 23:52:06.543 INFO [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
```
This happens with BIRT 4.12, 4.13 and 4.15 - found here: https://download.eclipse.org/birt/updates/release/4.14.0/index.html

What's wrong? Thank you for help in advance.

**Comment by speckyspooky** [comment]
The BIRT 4.14 release and the versions before doesn't support Tomcat 10.x
This is caused in the usage of JarkartaEE at Tomcat 10.x.
But BIRT is currently not migrated to JarkartaEE. The BIRT-viewer contains J2EE componends and this will cause the issues.

Some teams of the community modified BIRT 4.14 to get is runable under Tomcat 10 but this isn't currently supported by default.

**Comment by beccon4** [comment]
So with Tomcat 8 it should work?

**Comment by brush** [comment]
yes, tomcat8 or tomcat9 should not give you this error. (admittedly, i'm currently having some issues with a tomcat9 + birt 4.14 runtime, though it's not throwing errors on startup. but... that's another issue, literally!)

**Comment by speckyspooky** [comment]
Yes, I can confirm too, BIRT 4.14 is runable with Tomcat 8.x and 9.x.
