### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.w3c.tidy.Attribute.setNowrap(boolean)" because "org.w3c.tidy.AttributeTable.attrContent" is null

### ISSUE THREAD

**Issue by lasselindqvist** [eclipse-birt/birt#1619]
I have a random exception in report generation:

```
java.lang.NullPointerException: Cannot invoke "org.w3c.tidy.Attribute.setNowrap(boolean)" because "org.w3c.tidy.AttributeTable.attrContent" is null
	at org.w3c.tidy.AttributeTable.getDefaultAttributeTable(AttributeTable.java:459) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.w3c.tidy.Lexer.fixHTMLNameSpace(Lexer.java:1180) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.w3c.tidy.Lexer.setXHTMLDocType(Lexer.java:1239) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.w3c.tidy.Tidy.parse(Tidy.java:492) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.w3c.tidy.Tidy.parse(Tidy.java:263) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.w3c.tidy.Tidy.parseDOM(Tidy.java:335) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.parser.HTMLTextParser.parseHTML(HTMLTextParser.java:131) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.parser.TextParser.parse(TextParser.java:101) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.pdf.util.HTML2Content.processForeignData(HTML2Content.java:443) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.pdf.util.HTML2Content.html2Content(HTML2Content.java:429) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.nLayout.LayoutEngine.startForeign(LayoutEngine.java:585) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.emitter.CompositeContentEmitter.startForeign(CompositeContentEmitter.java:229) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.startContent(ContentEmitterUtil.java:76) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.startContent(HTMLTableLayoutEmitter.java:138) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.emitter.ContentEmitterAdapter.startForeign(ContentEmitterAdapter.java:169) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.startContent(ContentEmitterUtil.java:76) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer.startContent(HTMLPageBuffer.java:102) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.buffer.TableBreakBuffer.startContent(TableBreakBuffer.java:226) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLLeafItemLM.start(HTMLLeafItemLM.java:65) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:132) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.java:27) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLInlineStackingLM.resumeLayout(HTMLInlineStackingLM.java:97) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLInlineStackingLM.layoutNodes(HTMLInlineStackingLM.java:136) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.java:27) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.java:27) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLTableBandLM.layoutChildren(HTMLTableBandLM.java:62) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLStackingLM.layoutChildren(HTMLStackingLM.java:27) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLRepeatHeaderLM.layoutChildren(HTMLRepeatHeaderLM.java:54) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:133) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:97) ~[org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:145) [org.eclipse.birt.runtime-4.13.0.jar:?]
	at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.run(RunAndRenderTask.java:69) [org.eclipse.birt.runtime-4.13.0.jar:?]
```

I was unable to reproduce this reliably, but maybe the stack trace can give enough idea about what it could be.

**Comment by speckyspooky** [comment]
I will close the ticket. If we have further information and in best case a reference report then the issue can be reopend.
