### ISSUE TITLE
XLSX Emitter "Cannot add merged region" - again

### ISSUE THREAD

**Issue by doortokaos** [eclipse-birt/birt#1626]
I hoped my issue would be resolved with the fix for #1455, unfortunately it wasn't. So I have boiled it down to a simple report to reproduce my problem in 4.15: 
[excel_cell_merge.rptdesign.txt](https://github.com/eclipse-birt/birt/files/14883584/excel_cell_merge.rptdesign.txt)
In the report I already set the mentioned user property "ExcelEmitter.RemoveBlankRows" to false.

On creation of this report I get the following error:
```
Caused by: java.lang.IllegalStateException: Cannot add merged region A4:A8 to sheet because it overlaps with an existing merged region (A4:C4).
	at org.apache.poi.xssf.usermodel.XSSFSheet.validateMergedRegions(XSSFSheet.java:429)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:349)
	at org.apache.poi.xssf.usermodel.XSSFSheet.addMergedRegion(XSSFSheet.java:303)
	at uk.co.spudsoft.birt.emitters.excel.StyleManagerUtils.extendRows(StyleManagerUtils.java:1263)
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.interruptRow(AbstractRealTableRowHandler.java:233)
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.endRow(AbstractRealTableRowHandler.java:80)
	at uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.endRow(ExcelEmitter.java:409)
```

The source of the error is the dynamic text in the last row of the grid (a text element creates the same error):
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/08f71067-72f7-459f-9611-f67860d3af9d)

When I put this element outside the grid, the XLSX is rendered successfully and looks like this:
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/079d7410-003e-4798-ad2d-d0ae8a58997b)

By seeing the result of the successful I assume the XLSX emitter runs into the problem, because it tries to create a new column for the bullet points inside the merged grid cell.

When I change the report and split the last row to 3 cells instead of the merged one like this
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/dab57b77-25fe-4f09-8ada-a8112423d941)
the XLSX emitter creates the following output, which looks fine to me:
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/e742907a-1612-43c6-9d88-e0d2c03d2913)

So, if everything worked well, I would like to see this as result of the rendered report:
![grafik](https://github.com/eclipse-birt/birt/assets/22446825/d6a5448a-8a73-40a5-9ca8-494cda5d4af0)
The content of the dynamic text element as a big, single text in a merged cell over 3 columns.

**Comment by hvbtup** [comment]
> By seeing the result of the successful I assume the XLSX emitter runs into the problem, because it tries to create a new column for the bullet points inside the merged grid cell.

I think you are right here.

Probably the cell-merging cannot work with HTML content that creates a grid-like structure, in this case due to the bullet points.

BIRT is not perfect.
Support for HTML and CSS varies depending on the emitter.
In particular, you should not expect full support for LI or UL or TABLE structures.

One possible workaround (depending on the complexity of the HTML) could be to create a scripted data set which parses the text into lines, returning something like INDENT, BULLET, TEXT and then use a table item bound to this scripted data set inside your merged cell to render the line one after the other.

**Comment by doortokaos** [comment]
Yeah, but interestingly BIRT is able to create a nice output in the not merged context. So I don't quite understand why it doesn't merge the cell and then does the same thing with the dynamic text as in the non merged cell. In my opinion the splitting of the content should be done always or never and not if it is in a merged cell or not.

But you are right: in some case you would need to simplify the HTML or find other ways...

**Comment by hvbtup** [comment]
> In my opinion the splitting of the content should be done always or never and not if it is in a merged cell or not.
I think this is basically what's happening, but this conflicts with the merged cell.

**Comment by speckyspooky** [comment]
The problem is that your logic isn't the BIRT logic because leading is the wrapping element and not the content of the last leaf-element.
So because each behavior has to be implement the "inherited"-behavior and this is from root to leaf.
Therefore each element has his own implementation.

You "dynamic text" is special because you use an "unsorted list" and this will be handle in a grid or table like an table in a table cell. Of course there i a special handling of nested tables at cell level, therefore you can see the data on grid. 
As a single element we haven't any problem because it will be generated/handled like a kind of special table, therefore the own rows.

The version with the "dynamic text" into a grid with merged cell is the special version of a special version because then you have all. A nested tabled into a merged cell. The handling is complex at this moment and there are more constellation which can get such merge topic.

It needs a while to analyse your case and there is no guaranty that it will handle all cases because at the end this is not possible (for us).

**Comment by doortokaos** [comment]
Thanks for clarifying... As always: what seems a simple change in the result is a major pain to change in development.

Perhaps I have to setup a BIRT development environment, to take the next step after more than 10 years of designing more or less complex reports 😅

**Comment by speckyspooky** [comment]
I have debuged the topic and the error message is correct with in the current implementation because you have a span of cells and the unsorted list will be interpreted als merged structure too and then the POI library for excel think that you try to merge 2 joining areas.
Currently I haven't a good idea to solve this topic.

**Comment by speckyspooky** [comment]
I have created a PR to enhance the XLSX handling.
The first tries looks god but we need additional tests because it is a central change.

Here is a screen of your example with additional rows and an additional merged grid:

![xlsx-merge-cells](https://github.com/eclipse-birt/birt/assets/41593722/82b309c5-ea25-4978-9b38-5e908ee7f315)

**Comment by speckyspooky** [comment]
PR is merged to the master,
