### ISSUE TITLE
Can't generate Excel file: Could not auto-size column. Make sure the column was tracked prior to auto-sizing the column.

### ISSUE THREAD

**Issue by aremund** [eclipse-birt/birt#1703]
### Discussed in https://github.com/eclipse-birt/birt/discussions/1688

<div type='discussions-op-text'>

<sup>Originally posted by **p-schmidiger** May 16, 2024</sup>
We want to upgrade from BIRT 4.14.0 to BIRT 4.15.0. Now, while testing, we noticed that we cannot generate Excel reports.
The preview of an Excel report no longer works in the Birt Designer either.

I added my sample report: [WhiteSpaceTestReport.zip](https://github.com/eclipse-birt/birt/files/15332567/WhiteSpaceTestReport.zip)

We received the following error message:
Caused by: org.eclipse.birt.report.engine.api.EngineException: Error happened while running the report.
        at org.eclipse.birt.report.engine.api.impl.EngineTask.handleFatalExceptions(EngineTask.java:1867)
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:153)
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.run(RunAndRenderTask.java:69)
        ... 58 more
Caused by: java.lang.IllegalStateException: Could not auto-size column. Make sure the column was tracked prior to auto-sizing the column.
        at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1639)
        at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableHandler.endTable(AbstractRealTableHandler.java:181)
        at uk.co.spudsoft.birt.emitters.excel.handlers.TopLevelTableHandler.endTable(TopLevelTableHandler.java:62)
        at uk.co.spudsoft.birt.emitters.excel.ExcelEmitter.endTable(ExcelEmitter.java:381)
        at org.eclipse.birt.report.engine.emitter.CompositeContentEmitter.endTable(CompositeContentEmitter.java:175)
        at org.eclipse.birt.report.engine.layout.html.HTMLTableLayoutEmitter.endTable(HTMLTableLayoutEmitter.java:368)
        at org.eclipse.birt.report.engine.emitter.ContentEmitterUtil.endContent(ContentEmitterUtil.java:101)
        at org.eclipse.birt.report.engine.layout.html.buffer.AbstractNode.end(AbstractNode.java:65)
        at org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer._endContainer(HTMLPageBuffer.java:141)
        at org.eclipse.birt.report.engine.layout.html.buffer.HTMLPageBuffer.endContainer(HTMLPageBuffer.java:131)
        at org.eclipse.birt.report.engine.layout.html.buffer.TableBreakBuffer.endContainer(TableBreakBuffer.java:257)
        at org.eclipse.birt.report.engine.layout.html.HTMLTableLM.end(HTMLTableLM.java:49)
        at org.eclipse.birt.report.engine.layout.html.HTMLAbstractLM.layout(HTMLAbstractLM.java:134)
        at org.eclipse.birt.report.engine.layout.html.HTMLBlockStackingLM.layoutNodes(HTMLBlockStackingLM.java:66)
        at org.eclipse.birt.report.engine.layout.html.HTMLPageLM.layout(HTMLPageLM.java:92)
        at org.eclipse.birt.report.engine.layout.html.HTMLReportLayoutEngine.layout(HTMLReportLayoutEngine.java:97)
        at org.eclipse.birt.report.engine.api.impl.RunAndRenderTask.doRun(RunAndRenderTask.java:145)
        ... 60 more
Caused by: java.lang.IllegalStateException: Cannot get best fit column width on untracked column 0. Either explicitly track the column or track all columns.
        at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.getBestFitColumnWidth(AutoSizeColumnTracker.java:283)
        at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1636)
        ... 76 more
Caused by: java.lang.IllegalStateException: Column was never explicitly tracked and isAllColumnsTracked() is false (trackAllColumns() was never called or untrackAllColumns() was called after trackAllColumns() was called).
        at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.getBestFitColumnWidth(AutoSizeColumnTracker.java:280)
        ... 77 more

</div>

**Comment by aremund** [comment]
This problem occurs when generating the Excel using the streaming-option `ExcelEmitter.StreamingXlsx`. In the documentation for the SXSSFSheet https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/streaming/SXSSFSheet.html#autoSizeColumn-int-boolean- is says the following:

> Special note about SXSSF implementation: You must register the columns you wish to track with the SXSSFSheet using [trackColumnForAutoSizing(int)](https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/streaming/SXSSFSheet.html#trackColumnForAutoSizing-int-) or [trackAllColumnsForAutoSizing()](https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/streaming/SXSSFSheet.html#trackAllColumnsForAutoSizing--). This is needed because the rows needed to compute the column width may have fallen outside the random access window and been flushed to disk. Tracking columns is required even if all rows are in the random access window.

Since the columns are not registered for tracking first, aforementioned error is thrown when autosizing the columns.

Sadly, tracking comes with a performance penalty.
> Because determining the best-fit width for a cell is expensive, this may affect the performance.

Therefore, I suggest to just stop autosize the columns when having the streaming-option `ExcelEmitter.StreamingXlsx` enabled.

I will make a pull-request for that.
