### ISSUE TITLE
Out of memory error when creating a chart

### ISSUE THREAD

**Issue by wimjongman** [eclipse-birt/birt#1727]
Steps to reproduce

* Create a simple table with the customer table
* Drag a chart below the table
* Fill in X and Y

!ENTRY org.eclipse.ui 4 0 2024-06-11 11:35:50.977
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4058)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:451)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:262)
	at org.eclipse.swt.graphics.Image.directToDirect(Image.java:1791)
	at org.eclipse.swt.graphics.Image.init(Image.java:1897)
	at org.eclipse.swt.graphics.Image.init(Image.java:2111)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:497)
	at org.eclipse.birt.chart.reportitem.ui.DesignerRepresentation.paintChart(DesignerRepresentation.java:358)
	at org.eclipse.birt.chart.reportitem.ui.DesignerRepresentation.paintClientArea(DesignerRepresentation.java:324)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.birt.report.designer.internal.ui.editors.schematic.figures.ReportRootFigure.paintChildren(ReportRootFigure.java:121)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1312)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.ScalableFreeformLayeredPane.paintClientArea(ScalableFreeformLayeredPane.java:73)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1303)
	at org.eclipse.draw2d.Viewport.paintClientArea(Viewport.java:161)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)

**Comment by merks** [comment]
This is in the all-in-one product?  The following seems to be a relatively small value:

![image](https://github.com/eclipse-birt/birt/assets/208716/469adf8a-5fae-461c-820a-7a617c8423a7)

Does manually changing this in the birt.ini to a larger number help?

**Comment by wimjongman** [comment]
After close Eclipse will not restart.

[log.txt](https://github.com/user-attachments/files/15785925/log.txt)

**Comment by merks** [comment]
So it's running out of heap while restarting, trying to re-open the editor you had open.

Please try increasing the -Xmx...

**Comment by wimjongman** [comment]
After changing to 2GB I do not get the OOME but an IOOBE.

<details><summary>stack</summary>
java.lang.ArrayIndexOutOfBoundsException: Index 466020624 out of bounds for length 466020624
	at org.eclipse.swt.graphics.ImageData.blit(ImageData.java:1921)
	at org.eclipse.swt.graphics.Image.directToDirect(Image.java:1793)
	at org.eclipse.swt.graphics.Image.init(Image.java:1897)
	at org.eclipse.swt.graphics.Image.init(Image.java:2111)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:497)
	at org.eclipse.birt.chart.reportitem.ui.DesignerRepresentation.paintChart(DesignerRepresentation.java:358)
	at org.eclipse.birt.chart.reportitem.ui.DesignerRepresentation.paintClientArea(DesignerRepresentation.java:324)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.birt.report.designer.internal.ui.editors.schematic.figures.ReportRootFigure.paintChildren(ReportRootFigure.java:121)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1312)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.ScalableFreeformLayeredPane.paintClientArea(ScalableFreeformLayeredPane.java:73)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1303)
	at org.eclipse.draw2d.Viewport.paintClientArea(Viewport.java:161)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.DeferredUpdateManager.paint(DeferredUpdateManager.java:168)
	at org.eclipse.draw2d.LightweightSystem.paint(LightweightSystem.java:202)
	at org.eclipse.draw2d.LightweightSystem.lambda$0(LightweightSystem.java:110)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4285)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1184)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1169)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1540)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4769)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.UpdateWindow(Native Method)
	at org.eclipse.swt.widgets.Decorations.setVisible(Decorations.java:1293)
	at org.eclipse.swt.widgets.Shell.setVisible(Shell.java:2097)
	at org.eclipse.swt.widgets.Shell.open(Shell.java:1306)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.postProcess(WBWRenderer.java:741)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:711)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1079)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)

</details>

**Comment by merks** [comment]
Looking at this stack trace, the birt things it haven't changed for quite a few years, so that leaves draw2d and swt differences and the potential candidates.  

I would expect this to be reproducible with a debug launch...

**Comment by merks** [comment]
I'd like to be able to reproduce the problem.  Would it be possible to provide "idiot-resistant" steps? Or a zip with the project with the project and what should be opened to see the problem?

**Comment by wimjongman** [comment]
Please drop this report 
[customerreport.rptdesign.txt](https://github.com/user-attachments/files/15787271/customerreport.rptdesign.txt) in a report project. Then follow this video.


https://github.com/eclipse-birt/birt/assets/180969/657d79c3-cc1f-4df4-b5f9-560c478b673c

**Comment by wimjongman** [comment]
... remove the .txt extension after you dropped it.

**Comment by merks** [comment]
Sorry I was out for a while...

It's unhelpful, but debug launch worked okay:

![image](https://github.com/eclipse-birt/birt/assets/208716/c5622306-a38c-4e78-83e7-451aef5989fe)

I'll poke at it a bit more, including trying the actual unzipped product.

**Comment by merks** [comment]
It even works in the unzipped product for me.  

![image](https://github.com/eclipse-birt/birt/assets/208716/dcd3964c-f0d1-4bf9-8842-888f89cd60bb)

I'm on Windows 10 still.

I'm not sure what to make of this.  😞

**Comment by merks** [comment]
I tried a really long name too but no problems.

D:/Users/test36/birt-Downloads-birt-report-designer-all-in-one-4.16.0-202406071258-win32.win32.x86_64/eclipse/birt.exe

Maybe you can try not having it in the Downloads folder.

Unless I can reproduce the problem somewhere somehow, I'm not sure what to do.

BTW, here is the saved result.  I wonder if you have problems when you open that?

[customerreport-with-chart.rptdesign.txt](https://github.com/user-attachments/files/15791660/customerreport-with-chart.rptdesign.txt)

**Comment by merks** [comment]
BTW, I have this local modified version of BIRT.setup for generating the *.target I've been committing, but I have not commit the setup itself.  So you can use this locally to ensure that the target platform is exactly like the one used by the actual product built by Tycho:

[BIRT.setup.txt](https://github.com/user-attachments/files/15791696/BIRT.setup.txt)

**Comment by merks** [comment]
Of course I will hold of the release for this, but I am at a complete loss for how to help with a problem that I cannot reproduce...

I'll be a car soon until later in the afternoon so that also will limit my helpfulness today.

**Comment by speckyspooky** [comment]
Hi together, I have retested the latest milestone "BIRT 4.16.0 Milestone - S202406071258" with the "all in one designer" from my side with Windows 10.

I used the default download-link "[birt-report-designer-all-in-one-4.16.0-202406071258-win32.win32.x86_64.zip](https://www.eclipse.org/downloads/download.php?file=/birt/updates/milestone/S202406071258/downloads/birt-report-designer-all-in-one-4.16.0-202406071258-win32.win32.x86_64.zip)"

And changed nothing from my side and used your report @wimjongman 
According to your video I added the chart to the report and the result is:

![grafik](https://github.com/eclipse-birt/birt/assets/41593722/4728237d-cd9f-449a-8a18-c085bfb27b3b)

I didn't got the "event loop exception". I got only an information.
The preview could be created also the PDF & Excel.

Have you used your local dev-environment (with the latest changes) or our official download link?
If I have time I can test it this evening with my Windows 11 system.

**Comment by wimjongman** [comment]
Hi, thanks for testing. I have Windows 11.  I downloaded the milestone again. This time I extracted it outside Downloads with a shorter path

I opened Ed's report without any issues but as soon as I added a chart it failed again.


https://github.com/eclipse-birt/birt/assets/180969/8b0131b9-e0a8-4b7c-8d98-366b70af311f

**Comment by wimjongman** [comment]
After increasing the memory I get the 

java.lang.ArrayIndexOutOfBoundsException: Index 466020624 out of bounds for length 466020624
	at org.eclipse.swt.graphics.ImageData.blit(ImageData.java:1921)
	at org.eclipse.swt.graphics.Image.directToDirect(Image.java:1793)
	at org.eclipse.swt.graphics.Image.init(Image.java:1897)
	at org.eclipse.swt.graphics.Image.init(Image.java:2111)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:497)
	at org.eclipse.birt.chart.reportitem.ui.DesignerRepresentation.paintChart(DesignerRepresentation.java:358)
	at org.eclipse.birt.chart.reportitem.ui.DesignerRepresentation.paintClientArea(DesignerRepresentation.java:324)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.birt.report.designer.internal.ui.editors.schematic.figures.ReportRootFigure.paintChildren(ReportRootFigure.java:121)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1312)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)
	at org.eclipse.draw2d.Figure.paint(Figure.java:1229)
	at org.eclipse.draw2d.Figure.paintChildren(Figure.java:1275)
	at org.eclipse.draw2d.Figure.paintClientArea(Figure.java:1308)

**Comment by claesrosell** [comment]
1:24 into the movie the target size for chart is briefly visible. It is for some reason set to: 57225 x 286125 pt
What happens if you lower that a bit?

![bild](https://github.com/eclipse-birt/birt/assets/8941815/b963e183-5586-4e68-b12f-35659bf6a5db)

**Comment by hvbtup** [comment]
Just for info: In countries which use a decimal comma instead of a decimal point, editing sizes manually in the dialogs is often a matter of luck: Do I have to enter a point or a comma, and if so, is it interpreted as a decimal separator or as a thousands separator?
The huge width and height values might be a result of such a confusion.

**Comment by wimjongman** [comment]
@claesrosell When I change the size manually I can open the report without issues.

![image](https://github.com/eclipse-birt/birt/assets/180969/b414e628-7268-4448-91cb-fe5790c00b0d)

**Comment by wimjongman** [comment]
@claesrosell Thanks for finding the root cause. Now we need to figure out why it resizes to that format for me and not for the others. I have windows 11, but when I run it from a Launch configuration everything works as expected.

I will try the launch config with the new target platform Ed gave me.

**Comment by wimjongman** [comment]
@merks your new setup runs in an error

![image](https://github.com/eclipse-birt/birt/assets/180969/ebe13e87-afd9-480e-a8b2-4fec1d275436)

**Comment by merks** [comment]
The updated catalogs were promoted a few hours ago so I will need to make adjustments to the setup now. Which is hard to do from a speeding car.  I’ll be home in about 2 hours.  Perhaps try to  fiddle with an explicit -nl argument in the launch or in the unpackaged application to test that theory. 

@ ptziegler maybe this rings a bell?

**Comment by merks** [comment]
This version should work with the latest catalogs:

[BIRT.setup.txt](https://github.com/user-attachments/files/15804643/BIRT.setup.txt)

**Comment by merks** [comment]
When I look at sizes, they look the same as yours except yours are missing the '.':

![image](https://github.com/eclipse-birt/birt/assets/208716/a0de5558-c133-48aa-8096-77583bd6ef73)

**Comment by wimjongman** [comment]
That's it. @speckyspooky did you not change some things in the dimension calculations?

**Comment by merks** [comment]
I'm not sure what all uses org.eclipse.birt.core.format.NumberFormatter. 

https://github.com/eclipse-birt/birt/commit/495f928b93d59f03812dab74f7fbc71e7dd36995

That looks like a candidate to consider.

**Comment by speckyspooky** [comment]
Yes, the number format is changed from java.text.NumberFormat to com.ibm.icu.text.NumberFormat.
But I changed no dimension calculation. The change was done to support further number formats according to the original issue.


![grafik](https://github.com/eclipse-birt/birt/assets/41593722/2009620b-79d2-42e0-8127-572f0ee0a254)

**Comment by speckyspooky** [comment]
@wimjongman 

I have done the same steps from your video with the same version (see screen with the timestamps).
It is crazy because I haven't the effect. So it is unclear fro my if we use both the same zip-file of BIRT
which configuration (os configuration) cause your effect of the growing chart.

![grafik](https://github.com/eclipse-birt/birt/assets/41593722/c17b0368-4584-4d6f-9b1e-7c0b438e45d3)

**Comment by hvbtup** [comment]
Probably the issue is caused because ATM BIRT uses locale-dependent conversions in many places, but obviously not always in the right places. I mean, in some places, it should be local-dependent, but isn't, or in other places, it is local local-dependent, but shouldn't be. Implicit type conversions can add additional issues (mostly in JS, though).

From my POV, errors like this could be avoided if *everywhere* we convert between strings and numbers, e.g. for showing and editing sizes, we would use the locale-independent basic Java functions that are meant for this, e.g. `Float.valueOf(s)` and `toString(f)`. I think such an approach is generally easier.
Then it would be clear that a dot always means the decimal point  and there cannot be a thousands separator; thus "123.456" always means one hundred and twenty-three plus a fraction, not 123 thousand.
BIRT is meant for people with a technical background, and the users will understand this.
And if locale dependent conversion is used, are we sure that we use the correct locale everywhere?

**Comment by hvbtup** [comment]
BTW many standards (eg. EN ISO 80000) say that (preferably narrower) spaces should be used as a thousands separator, to avoid such confusion. However, at least in Germany, for _monetary amounts_, a decimal comma is commonly used; in Switzerland an apostrophe (which also avoids confusion).

This comment and my previous comment are meant for readers from other countries (e.g. USA) which might not be aware of these intricacies. Of course Wim, Ed and Thomas know about this.

**Comment by wimjongman** [comment]
The issue is somewhere in ChartReportItemUIImpl.resizeToFitContainer but I can't pinpoint it

Everything works when I add 

    -nl 
    en_US

it fails when I leave the -nl flag or add 

    -nl nl

**Comment by merks** [comment]
@wimjongman 

Indeed, I was about to suggest this is where things are going wrong because before then the size is like this:

![image](https://github.com/eclipse-birt/birt/assets/208716/7a2a6a39-5fde-42c6-a16e-c8366476f62f)

**Comment by merks** [comment]
I think is probably quite bad:

![image](https://github.com/eclipse-birt/birt/assets/208716/d1806c14-364d-424d-909e-f8dd0ef3cfa3)

Given I see the units are "pt" and don't think a comma value is correct here.

**Comment by merks** [comment]
But, all that being said, it doesn't actually crash for me...

**Comment by hvbtup** [comment]
This is what I mean with "confusion".
The root cause of this may be the fact that the value contains a string which should be parsed as a number and a unit.
IMHO, such a string should _always_ use a decimal point and no thousands separator, because basically it is a CSS value and there is no "locale" concept for such values.
Thus the correct value should be `572.25pt`. Can you find out where the value is set and why it uses a comma?

**Comment by merks** [comment]
Later it is doing things properly:

![image](https://github.com/eclipse-birt/birt/assets/208716/8b83b0df-6cf7-4590-8aac-1c405891acc8)

This is where it's using the locale-specific fomatter:

![image](https://github.com/eclipse-birt/birt/assets/208716/bb59b77b-eac7-4482-87e0-1b0b2f5445bf)

But later parses with the locale as well while validating:

![image](https://github.com/eclipse-birt/birt/assets/208716/84bb88a1-118c-49c9-866c-e0ee5144666e)

**Comment by merks** [comment]
Even here it looks okay still:

![image](https://github.com/eclipse-birt/birt/assets/208716/67343be5-a6a0-43cf-8de1-68e637d8b479)

I.e., that it properly sets a value that uses a ".".

Somehow in Wim's case I think this is kind of removing the comma rather than parsing it correctly, but I can't replicate that.

**Comment by merks** [comment]
@hvbtup 

I agree with the locale-specific concerns.  It's a nightmare, but not easily unraveled at this point in the game.  😱

**Comment by merks** [comment]
@wimjongman 

BTW, I was trying -nl nl_NL to be more like en_US.

**Comment by merks** [comment]
@wimjongman 

FYI, I also tried to launch like this to maybe replicate what happens when the locale is determine directly from the environment but still I can't replicate the problem even though I see it using "," values:

![image](https://github.com/eclipse-birt/birt/assets/208716/99bf3432-228e-4c93-848a-f5f045179365)

I don't think I can help further.  😭

**Comment by hvbtup** [comment]
Maybe Wim can use the debugger and look at the same steps like Ed, but in his environment?

**Comment by wimjongman** [comment]
Any -nl value that I set is fine -nl nl -nl en_US 

When I don't set -nl is where it bombs

**Comment by merks** [comment]
What is the value of the LC_CTYPE environment variable in your environment?  Mine is `LC_CTYPE=en_US.UTF-8`...

**Comment by wimjongman** [comment]
> What is the value of the LC_CTYPE environment variable in your environment? Mine is `LC_CTYPE=en_US.UTF-8`...

I do not have this property. 

### Suggested workaround
What i see today is that it fails in my situation when there is no -nl flag in the ini file. When I put the flag the situation is resolved.

I think we can just add the -nl flag to the generated ini and then release.

**Comment by merks** [comment]
The -nl is followed by the locale.  I don't think setting it to en_US is a proper solution.

What does sysinfo tell you?

![image](https://github.com/eclipse-birt/birt/assets/208716/a4417578-6dd0-4383-8da6-46dd47924250)

It just seems to me if you can reproduce it under debug control we should be able to find out where things go wrong.  😢 

Is the local that does the formatting really nl_NL and not something else/strange in the case it break?

![image](https://github.com/eclipse-birt/birt/assets/208716/3259c911-52bf-48be-86d4-ef8663bb9c7c)

**Comment by merks** [comment]
We cannot just add an -nl to the product to work around a problem that appears to happen on only your machine.

**Comment by wimjongman** [comment]
> We cannot just add an -nl to the product to work around a problem that appears to happen on only your machine.

Yes, I did not think this true. We do not have an installer that can set it.

**Comment by merks** [comment]
Certainly one can add arguments to the product definition but  the -nl requires to specify a locale:

![image](https://github.com/eclipse-birt/birt/assets/208716/dbaa79e6-cce6-4053-ab58-a72c92d0a9b3)

We must get to the bottom of this....

**Comment by wimjongman** [comment]
Here are the props in my failing setting

 osgi.nl = en_US
 osgi.os = win32
 osgi.ws = win32
 path.separator = ;
 stderr.encoding = UTF-8
 stdout.encoding = UTF-8
 sun.arch.data.model = 64
 sun.boot.library.path = C:\Users\jongw\.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_22.0.1.v20240426-1149\jre\bin
 sun.cpu.endian = little
 sun.cpu.isalist = amd64
 sun.io.unicode.encoding = UnicodeLittle
 sun.jnu.encoding = UTF-8
 sun.management.compiler = HotSpot 64-Bit Tiered Compilers
 sun.os.patch.level = 
 user.country = US
 user.country.format = NL
 user.language = en
 user.name = jongw
 user.script = 
 user.timezone =

**Comment by wimjongman** [comment]
![image](https://github.com/eclipse-birt/birt/assets/180969/b3287a86-de76-4317-9597-7dd7c803bfb9)

**Comment by wimjongman** [comment]
if I do Locale.getLocales() the en_NL is not in that list.

**Comment by wimjongman** [comment]
These nl locales are listed

* nl_NL
* nl_NL_#Latn
* nl_AW
* nl_BE
* nl_BQ
* nl_CW
* nl_SR
* nl_SX

**Comment by wimjongman** [comment]
If I add nl_PP or nl_EN or en_NL explicitly then everything is ok.

**Comment by merks** [comment]
The property combination is really odd!  
```
user.country = US
user.country.format = NL
user.language = en
```

**Comment by wimjongman** [comment]
Ok, I found a solution.
