### ISSUE TITLE
Invalid signature error in runtime tests

### ISSUE THREAD

**Issue by merks** [eclipse-birt/birt#1819]
Currently the master builds are failing like this:
```
[ERROR] org.eclipse.birt.sdk.RuntimeTest.testChart -- Time elapsed: 0.161 s <<< ERROR!
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:347)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:289)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:283)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:239)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:761)
	at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1037)
	at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:883)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:491)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
```
I suspect it's the result of the changes to the signing service:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4680#note_2548374

**Comment by merks** [comment]
The signature files look different (have different names) with the latest signing service:

![image](https://github.com/user-attachments/assets/68fb39f2-a241-48ff-a901-7c3446996889)

**Comment by merks** [comment]
That being said, older successful showed this:
```
[INFO]  [buildJar] load bundle uk.co.spudsoft.birt.emitters.excel from uk.co.spudsoft.birt.emitters.excel_4.17.0.v202407201614
Jul 22, 2024 1:11:33 PM org.eclipse.birt.build.pack.FrameworkPacker log
WARNING: duplicate org.eclipse.birt.chart.device.pdf/META-INF/ECLIPSE_.SF
Jul 22, 2024 1:11:33 PM org.eclipse.birt.build.pack.FrameworkPacker log
WARNING: duplicate org.eclipse.birt.chart.device.pdf/META-INF/ECLIPSE_.RSA
```
Probably original the name was ECLIPSEF and was intended to be filtered out:

https://github.com/eclipse-birt/birt/blob/5f379b5b7dc7fffaff546b944adfe3ca1067aa08/build/org.eclipse.birt.build/src/org/eclipse/birt/build/ant/PackTask.java#L183C7-L186

I will try to enhance the filter.

**Comment by merks** [comment]
I noticed this now as well:

![image](https://github.com/user-attachments/assets/b899b3b9-02e7-4b15-86b7-c4a64dc0c955)

So the last time this was a problem, more than 9 years ago, it wasn't fixed by fixing the ant task implementation but by post-processing the jar produced by that task.  Such a tangled web was woven...

**Comment by merks** [comment]
The above ant hack will also be cleaned up.

Thank goodness the tests for the runtimes were enabled, otherwise someone downstream would have noticed this at some later point in time, do doubt when it's least convenient rather than the day after the signing service was updated.

**Comment by merks** [comment]
The signature file names might be changed back to ECLIPSE_ but I already changed the pattern to accommodate that name as well:
```
"(.*\\.jar/)?META-INF/(ECLIPSEF|ECLIPSE_|CODESIGN)\\..*"
```

**Comment by hvbtup** [comment]
Ed, I really admire your endurance and your work...
