### ISSUE TITLE
Creating/Editing datacubes  leads to error

### ISSUE THREAD

**Issue by cszasz** [eclipse-birt/birt#1824]
When I try to drop a datacube into the page I get the following error:

An unexpected internal exception occurred. Please see log for detail.
  Plug-in Provider:Eclipse BIRT Project
  Plug-in Name:BIRT Designer UI
  Plug-in ID:org.eclipse.birt.report.designer.ui
  Version:4.16.0.v202406131946
  Error Code:Error.GUIException.invokedByUnexpectedException
  Error Message:class org.eclipse.birt.report.designer.internal.ui.layout.TableLayout cannot be cast to class org.eclipse.draw2d.XYLayout (org.eclipse.birt.report.designer.internal.ui.layout.TableLayout is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1fba8abc; org.eclipse.draw2d.XYLayout is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @44c39f17)

The same happens if I try to open an existing one created before when the functionility was not yet broken.

**Comment by merks** [comment]
Can you try with 4.17?

**Comment by cszasz** [comment]
When can I install it from?

**Comment by merks** [comment]
https://download.eclipse.org/birt/updates/nightly/latest

**Comment by cszasz** [comment]
The same result. I get this when I open a report which already has datacubes:

java.lang.ClassCastException: class org.eclipse.birt.report.designer.internal.ui.layout.TableLayout cannot be cast to class org.eclipse.draw2d.XYLayout (org.eclipse.birt.report.designer.internal.ui.layout.TableLayout is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @52fcc94c; org.eclipse.draw2d.XYLayout is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @46c1c848)
	at org.eclipse.birt.report.item.crosstab.internal.ui.editors.editparts.CrosstabTableEditPart.createEditPolicies(CrosstabTableEditPart.java:215)
	at org.eclipse.gef.editparts.AbstractEditPart.addNotify(AbstractEditPart.java:256)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addNotify(AbstractGraphicalEditPart.java:227)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:219)
	at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:788)
	at org.eclipse.birt.report.designer.internal.ui.editors.schematic.editparts.ReportElementEditPart.refreshChildren(ReportElementEditPart.java:556)
	at org.eclipse.gef.editparts.AbstractEditPart.refresh(AbstractEditPart.java:740)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.refresh(AbstractGraphicalEditPart.java:620)
	at org.eclipse.gef.editparts.AbstractEditPart.addNotify(AbstractEditPart.java:258)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addNotify(AbstractGraphicalEditPart.java:227)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:219)
	at org.eclipse.gef.editparts.SimpleRootEditPart.setContents(SimpleRootEditPart.java:116)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setContents(AbstractEditPartViewer.java:657)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.setContents(AbstractEditPartViewer.java:666)
	at org.eclipse.birt.report.designer.internal.ui.editors.layout.ReportEditorWithPalette.setContents(ReportEditorWithPalette.java:543)
	at org.eclipse.birt.report.designer.internal.ui.editors.layout.ReportEditorWithPalette.initializeGraphicalViewer(ReportEditorWithPalette.java:533)
	at org.eclipse.birt.report.designer.internal.ui.editors.parts.GraphicalEditorWithFlyoutPalette.createGraphicalViewer(GraphicalEditorWithFlyoutPalette.java:685)
	at org.eclipse.birt.report.designer.internal.ui.editors.layout.ReportEditorWithPalette.createGraphicalViewer(ReportEditorWithPalette.java:570)
	at org.eclipse.birt.report.designer.internal.ui.editors.layout.ReportEditorWithRuler.createGraphicalViewer(ReportEditorWithRuler.java:80)
	at org.eclipse.gef.ui.parts.GraphicalEditor.createPartControl(GraphicalEditor.java:153)
	at org.eclipse.birt.report.designer.internal.ui.editors.parts.GraphicalEditorWithFlyoutPalette.createPartControl(GraphicalEditorWithFlyoutPalette.java:495)
	at org.eclipse.birt.report.designer.ui.editors.pages.ReportLayoutEditorFormPage.createPartControl(ReportLayoutEditorFormPage.java:211)
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:480)
	at org.eclipse.birt.report.designer.ui.editors.AbstractMultiPageEditor.pageChange(AbstractMultiPageEditor.java:32)
	at org.eclipse.birt.report.designer.ui.editors.MultiPageReportEditor.pageChange(MultiPageReportEditor.java:736)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1030)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:612)
	at org.eclipse.birt.report.designer.ui.editors.MultiPageReportEditor.setActivePage(MultiPageReportEditor.java:1377)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:337)
	at org.eclipse.birt.report.designer.ui.editors.ReportEditorProxy.createPartControl(ReportEditorProxy.java:143)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:976)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:938)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:138)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:385)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:311)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:203)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:105)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5249)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:208)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:206)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:661)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:625)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:796)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1270)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3233)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:3123)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3121)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3091)
	at org.eclipse.ui.actions.OpenWithMenu.openEditor(OpenWithMenu.java:325)
	at org.eclipse.ui.actions.OpenWithMenu.lambda$0(OpenWithMenu.java:182)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4412)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3988)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

**Comment by merks** [comment]
Thanks for reporting and checking. We’ll look into it shortly.

**Comment by cszasz** [comment]
I realized the error I made. When installing there are plugins which shouldn't be installed into the IDE. But by mistake I installed them as well. They cause this error.

**Comment by cszasz** [comment]
However after I installed the wrong feature as well is there a way to uninstall them completely. Simply uninstalling the BIRT features seems to have left something behind as I get the same error event after reinstalling only the correct features.

**Comment by cszasz** [comment]
I turned out that it works ok with previous eclipse versions, but with the latest eclipse, it produces the above error even after a completely fresh install.

**Comment by merks** [comment]
I could reproduce the problem in the debugger.  I suspect there are changes in GEF that are causing this issue so depending on which version of GEF you have installed, there can be problems probably with with any version of BIRT.  I think I have a fix coming soon...

**Comment by merks** [comment]
The latest nightly build fixes the problem 

https://download.eclipse.org/birt/updates/nightly/latest

**Comment by digiPHOTO-it** [comment]
good. this worked for me.
excellent
