### ISSUE TITLE
Fix launch configurations

### ISSUE THREAD

**Issue by SteveSchafer-Innovent** [eclipse-birt/birt#991]
@wimjongman I'm getting this error again with 4.10 master:

!ENTRY org.eclipse.equinox.launcher 4 0 2022-06-02 12:01:35.047
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

I'd appreciate it if you could describe the steps you take to update a stale run configuration.

**Comment by wimjongman** [comment]
Steve, I typically open the target file and "Reload target platform".

![image](https://user-images.githubusercontent.com/180969/176948486-ba0538a7-1ebf-427a-9b58-f8d8de6bf981.png)

Then I rebuild everything.

![image](https://user-images.githubusercontent.com/180969/176948532-6a9f7cf1-4e32-4b00-89ae-143d2f6a0ea0.png)


Sometimes I go to the target platform preferences and reload from there. 

![image](https://user-images.githubusercontent.com/180969/176948650-84ab3c8e-c81a-4b6c-8325-d2e8daba33cd.png)

The issue could also be an out-of-date run config. Open the run config and "Add Required"  / "Validate"

![image](https://user-images.githubusercontent.com/180969/176948809-92f5621c-d4bd-4871-9f10-0e16293ec4db.png)

**Comment by speckyspooky** [comment]
The requested steps are documented.
